name: pull request

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Define the type of runner and golang version
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    # Define steps for this job
    steps:
      # Install predefined golang version
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup docker multi arch builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      # Get git short commit hash
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # Runs a single command using the runners shell
      - name: Run go test
        run: go test -v -cover

      - name: Build artifact for e2e tests
        run: go build -o ./arpad

      - name: e2e test
        run: ./arpad -scan-period=1s | grep "k8s.gcr.io" -m 1 # Run the scanner and exit on the first find

      # Build docker container and push to registry
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: false
          tags: |
            ghcr.io/hunok/arpad:${{ steps.vars.outputs.sha_short }}
